const { Schema, model } = require('mongoose');

const MoviesSchema = new Schema({
    adult:{
        type:Boolean
    },
    backdrop_path:{
        type:String,
        required:true,
    },
    genre_ids:{
        type:Array,
        requied:true
    },
    id:{
        type:String,
        required:true
    },
    original_language:{
        type:String,
        required:true  
    },
    original_title:{
        type:String,
        required:true
    },
    overview:{
        type:String,
        required:true
    },
    popularity:{
        type:String,
        required:true
    },
    poster_path:{
        type:String,
        required:true
    },
    realease_date:{
        type:String,
        required:true
    },
    title:{
        type:String,
        required:true
    },
    video:{
        type:Boolean,
    },
    vote_average:{
        type:Number,
        required:true
    },
    vote_count:{
        type:Number,
        required:true
    }
})